version: '3'

tasks:
  setup:
    desc: Set up Python and install dependencies
    cmds:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  unit-tests:
    desc: Run unit tests
    cmds:
      - pytest tests/test_square.py
      - pytest tests/test_hello.py

  integration-tests:
    desc: Run integration tests
    cmds:
      - pytest tests/test_database_operations.py -v
      - pytest tests/test_int_test_dbconn.py -v
      - pytest tests/test_main.py -v
      - pytest tests/test_main_fastapi.py -v

  test:
    desc: Run all tests (unit + integration)
    cmds:
      - task: setup
      - task: unit-tests
      - task: integration-tests